/**
 * oaep.ts — RSA-OAEP via WebCrypto API (Panel 2).
 *
 * Uses real 2048-bit and 4096-bit RSA key pairs generated by the browser.
 * Encryption is RSA-OAEP with SHA-256 (RFC 8017 §7.1, FIPS 186-4).
 * Demonstrates randomized encryption and OAEP padding structure.
 *
 * NIST SP 800-57 Part 1 Rev. 5 — 2048-bit minimum, 3072+ for long-term.
 */

import { announce, show, setText, setLoading, toBase64, truncate } from './ui.js';

interface OaepKeyPair {
  publicKey:  CryptoKey;
  privateKey: CryptoKey;
  bits: number;
}

const oaepKeys: Record<number, OaepKeyPair | null> = { 2048: null, 4096: null };
let lastCiphertext: ArrayBuffer | null = null;
let lastCiphertextBits = 0;

export function initOaepPanel(): void {
  (document.getElementById('oaep-gen-2048') as HTMLButtonElement)
    .addEventListener('click', () => generateKey(2048));
  (document.getElementById('oaep-gen-4096') as HTMLButtonElement)
    .addEventListener('click', () => generateKey(4096));

  (document.getElementById('oaep-encrypt-2048') as HTMLButtonElement)
    .addEventListener('click', () => doEncrypt(2048));
  (document.getElementById('oaep-encrypt-4096') as HTMLButtonElement)
    .addEventListener('click', () => doEncrypt(4096));

  (document.getElementById('oaep-decrypt-2048') as HTMLButtonElement)
    .addEventListener('click', () => doDecrypt(2048));
  (document.getElementById('oaep-decrypt-4096') as HTMLButtonElement)
    .addEventListener('click', () => doDecrypt(4096));

  (document.getElementById('oaep-randomize') as HTMLButtonElement)
    .addEventListener('click', demonstrateRandomization);
}

/* ── Key Generation ─────────────────────────────────────────── */
async function generateKey(bits: 2048 | 4096): Promise<void> {
  const btnId = `oaep-gen-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const originalLabel = btn.getAttribute('aria-label') ?? `Generate ${bits}-bit RSA key`;
  setLoading(btn, true);
  announce(`Generating ${bits}-bit RSA-OAEP key pair via WebCrypto…`);

  const t0 = performance.now();
  try {
    const pair = await crypto.subtle.generateKey(
      {
        name: 'RSA-OAEP',
        modulusLength: bits,
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]), // 65537
        hash: 'SHA-256',
      },
      false, // non-extractable private key (security best practice)
      ['encrypt', 'decrypt'],
    ) as CryptoKeyPair;

    const kgTime = Math.round(performance.now() - t0);
    oaepKeys[bits] = {
      publicKey:  pair.publicKey,
      privateKey: pair.privateKey,
      bits,
    };

    // Update timing
    setText(`oaep-${bits}-kg-time`, String(kgTime));
    show(`oaep-${bits}-timing`);

    // Enable encrypt buttons
    (document.getElementById('oaep-encrypt-2048') as HTMLButtonElement).disabled = !oaepKeys[2048];
    (document.getElementById('oaep-encrypt-4096') as HTMLButtonElement).disabled = !oaepKeys[4096];

    show('oaep-encrypt-card');
    announce(`${bits}-bit RSA-OAEP key pair generated in ${kgTime} ms.`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Key generation failed: ${msg}`);
  } finally {
    setLoading(btn, false, originalLabel);
  }
}

/* ── Encrypt ────────────────────────────────────────────────── */
async function doEncrypt(bits: 2048 | 4096): Promise<void> {
  const kp = oaepKeys[bits];
  if (!kp) { announce('Generate the key first.'); return; }

  const input = document.getElementById('oaep-plaintext') as HTMLTextAreaElement;
  const pt = new TextEncoder().encode(input.value);

  // OAEP-SHA256 max plaintext: k − 2*hLen − 2 bytes = modBytes − 66 bytes
  const maxBytes = bits / 8 - 66;
  if (pt.length > maxBytes) {
    announce(`Message too long. Maximum ${maxBytes} bytes for ${bits}-bit key with SHA-256.`);
    return;
  }

  const btnId = `oaep-encrypt-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce(`Encrypting with RSA-${bits}-OAEP…`);

  const t0 = performance.now();
  try {
    const ct = await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt);
    const encTime = Math.round(performance.now() - t0);

    lastCiphertext     = ct;
    lastCiphertextBits = bits;

    const b64 = toBase64(new Uint8Array(ct));
    setText('oaep-ciphertext', b64);
    show('oaep-encrypt-result');

    // Update timing
    setText(`oaep-${bits}-enc-time`, String(encTime));

    // Enable decrypt buttons
    (document.getElementById('oaep-decrypt-2048') as HTMLButtonElement).disabled = bits !== 2048;
    (document.getElementById('oaep-decrypt-4096') as HTMLButtonElement).disabled = bits !== 4096;

    show('oaep-decrypt-card');
    show('oaep-randomize-card');
    announce(`Encrypted in ${encTime} ms. Ciphertext is ${ct.byteLength} bytes.`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Encryption failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}

/* ── Decrypt ────────────────────────────────────────────────── */
async function doDecrypt(bits: 2048 | 4096): Promise<void> {
  const kp = oaepKeys[bits];
  if (!kp || !lastCiphertext) { announce('Encrypt a message first.'); return; }
  if (lastCiphertextBits !== bits) {
    announce(`Ciphertext was encrypted with ${lastCiphertextBits}-bit key. Cannot decrypt with ${bits}-bit key.`);
    return;
  }

  const btnId = `oaep-decrypt-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce(`Decrypting with RSA-${bits}-OAEP…`);

  const t0 = performance.now();
  try {
    const pt = await crypto.subtle.decrypt({ name: 'RSA-OAEP' }, kp.privateKey, lastCiphertext);
    const decTime = Math.round(performance.now() - t0);
    const text = new TextDecoder().decode(pt);

    // Update timing
    setText(`oaep-${bits}-dec-time`, String(decTime));

    // Show result
    const outputEl = document.getElementById('oaep-decrypt-output') as HTMLElement;
    const statusEl = document.getElementById('oaep-decrypt-status') as HTMLElement;
    const textEl   = document.getElementById('oaep-decrypt-text')   as HTMLElement;

    outputEl.classList.add('result-box-success');
    statusEl.textContent = `✓ Decryption successful (${decTime} ms)`;
    textEl.textContent   = text;
    show('oaep-decrypt-output');
    announce(`Decrypted successfully in ${decTime} ms. Recovered: "${text}"`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    const outputEl = document.getElementById('oaep-decrypt-output') as HTMLElement;
    const statusEl = document.getElementById('oaep-decrypt-status') as HTMLElement;
    const textEl   = document.getElementById('oaep-decrypt-text')   as HTMLElement;

    outputEl.className = 'result-box result-box-error';
    statusEl.textContent = '✗ Decryption failed';
    textEl.textContent   = msg;
    show('oaep-decrypt-output');
    announce(`Decryption failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}

/* ── Randomization demo ─────────────────────────────────────── */
async function demonstrateRandomization(): Promise<void> {
  // Use whichever key pair is available
  const bits: 2048 | 4096 = oaepKeys[2048] ? 2048 : oaepKeys[4096] ? 4096 : 2048;
  const kp = oaepKeys[bits];
  if (!kp) {
    announce('Generate a key pair first.');
    return;
  }

  const input = document.getElementById('oaep-plaintext') as HTMLTextAreaElement;
  const pt = new TextEncoder().encode(input.value);
  const maxBytes = bits / 8 - 66;
  if (pt.length > maxBytes) {
    announce('Message too long for randomization demo.');
    return;
  }

  const btn = document.getElementById('oaep-randomize') as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce('Encrypting same message twice to demonstrate randomization…');

  try {
    const [ct1, ct2] = await Promise.all([
      crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt),
      crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt),
    ]);

    const b64_1 = toBase64(new Uint8Array(ct1));
    const b64_2 = toBase64(new Uint8Array(ct2));
    const match = b64_1 === b64_2;

    setText('oaep-ct1-short', truncate(b64_1, 52));
    setText('oaep-ct2-short', truncate(b64_2, 52));

    const matchEl = document.getElementById('oaep-ct-match') as HTMLElement;
    matchEl.textContent = match ? '⚠ YES (unexpected)' : '✓ NO — different every time';
    matchEl.style.color = match ? 'var(--c-danger)' : 'var(--c-safe)';

    show('oaep-randomize-result');
    announce(
      match
        ? 'Warning: ciphertexts matched unexpectedly.'
        : 'Confirmed: two encryptions of the same plaintext produce different ciphertexts.',
    );
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Randomization demo failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}
