/**
 * oaep.ts — RSA-OAEP via WebCrypto API (Panel 2).
 *
 * Uses real 2048-bit and 4096-bit RSA key pairs generated by the browser.
 * Encryption is RSA-OAEP with SHA-256 (RFC 8017 §7.1, FIPS 186-4).
 * Demonstrates randomized encryption and OAEP padding structure.
 *
 * NIST SP 800-57 Part 1 Rev. 5 — 2048-bit minimum, 3072+ for long-term.
 */

import { announce, show, setText, setLoading, toBase64, toHex, truncate } from './ui.js';
import { oaepEncode, type OaepFields } from './oaep-encode.js';

interface OaepKeyPair {
  publicKey:  CryptoKey;
  privateKey: CryptoKey;
  bits: number;
}

const oaepKeys: Record<number, OaepKeyPair | null> = { 2048: null, 4096: null };
let lastCiphertext: ArrayBuffer | null = null;
let lastCiphertextBits = 0;
let lastOaepFields: OaepFields | null = null;

export function initOaepPanel(): void {
  (document.getElementById('oaep-gen-2048') as HTMLButtonElement)
    .addEventListener('click', () => generateKey(2048));
  (document.getElementById('oaep-gen-4096') as HTMLButtonElement)
    .addEventListener('click', () => generateKey(4096));

  (document.getElementById('oaep-encrypt-2048') as HTMLButtonElement)
    .addEventListener('click', () => doEncrypt(2048));
  (document.getElementById('oaep-encrypt-4096') as HTMLButtonElement)
    .addEventListener('click', () => doEncrypt(4096));

  (document.getElementById('oaep-decrypt-2048') as HTMLButtonElement)
    .addEventListener('click', () => doDecrypt(2048));
  (document.getElementById('oaep-decrypt-4096') as HTMLButtonElement)
    .addEventListener('click', () => doDecrypt(4096));

  (document.getElementById('oaep-randomize') as HTMLButtonElement)
    .addEventListener('click', demonstrateRandomization);

  initOaepDiagramHover();
}

/* ── Diagram hover with real bytes ─────────────────────────── */
const OAEP_FIELD_LABELS: Record<string, string> = {
  leading:    '0x00 leading byte',
  maskedSeed: 'maskedSeed = seed XOR seedMask',
  maskedDB:   'maskedDB = DB XOR dbMask',
  lHash:      'lHash = SHA-256("")',
  ps:         'PS — zero padding string',
  separator:  '0x01 separator byte',
  M:          'M — your plaintext bytes',
  seed:       'seed — random hLen bytes',
  dbMask:     'dbMask = MGF1(seed, k − hLen − 1)',
  seedMask:   'seedMask = MGF1(maskedDB, hLen)',
};

function fieldBytes(fields: OaepFields, name: string): Uint8Array | null {
  switch (name) {
    case 'leading':    return new Uint8Array([0x00]);
    case 'maskedSeed': return fields.maskedSeed;
    case 'maskedDB':   return fields.maskedDB;
    case 'lHash':      return fields.lHash;
    case 'ps':         return fields.ps;
    case 'separator':  return fields.separator;
    case 'M':          return fields.M;
    case 'seed':       return fields.seed;
    case 'dbMask':     return fields.dbMask;
    case 'seedMask':   return fields.seedMask;
    default:           return null;
  }
}

function formatHexGrouped(bytes: Uint8Array, max = 64): string {
  if (bytes.length === 0) return '(empty)';
  const shown = bytes.subarray(0, max);
  const groups: string[] = [];
  for (let i = 0; i < shown.length; i += 4) {
    groups.push(toHex(shown.subarray(i, i + 4)));
  }
  let out = groups.join(' ');
  if (bytes.length > max) out += `  …(+${bytes.length - max} more bytes)`;
  return out;
}

function initOaepDiagramHover(): void {
  const tooltip = document.getElementById('oaep-tooltip') as HTMLElement | null;
  if (!tooltip) return;
  const labelEl = document.getElementById('oaep-tooltip-label') as HTMLElement;
  const bytesEl = document.getElementById('oaep-tooltip-bytes') as HTMLElement;
  const segments = document.querySelectorAll<HTMLElement>('[data-oaep-field]');

  const positionTooltip = (target: HTMLElement) => {
    const parent = tooltip.parentElement!;
    const parentRect = parent.getBoundingClientRect();
    const targetRect = target.getBoundingClientRect();
    const left = targetRect.left - parentRect.left;
    const top  = targetRect.bottom - parentRect.top + 6;
    tooltip.style.left = `${Math.max(8, Math.min(left, parent.clientWidth - 360))}px`;
    tooltip.style.top  = `${top}px`;
  };

  const show = (target: HTMLElement) => {
    const field = target.dataset.oaepField!;
    labelEl.textContent = OAEP_FIELD_LABELS[field] ?? field;
    if (!lastOaepFields) {
      bytesEl.innerHTML = '<span class="diagram-tooltip-empty">Run an OAEP encryption above to see real bytes here.</span>';
    } else {
      const bytes = fieldBytes(lastOaepFields, field);
      if (!bytes) {
        bytesEl.textContent = '(no data)';
      } else {
        bytesEl.textContent = `${bytes.length} bytes:  ${formatHexGrouped(bytes)}`;
      }
    }
    positionTooltip(target);
    tooltip.classList.add('visible');
  };

  const hide = () => tooltip.classList.remove('visible');

  segments.forEach(seg => {
    seg.addEventListener('mouseenter', () => show(seg));
    seg.addEventListener('mouseleave', hide);
    seg.addEventListener('focus',      () => show(seg));
    seg.addEventListener('blur',       hide);
    seg.tabIndex = 0;
  });
}

/* ── Key Generation ─────────────────────────────────────────── */
async function generateKey(bits: 2048 | 4096): Promise<void> {
  const btnId = `oaep-gen-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const originalLabel = btn.getAttribute('aria-label') ?? `Generate ${bits}-bit RSA key`;
  setLoading(btn, true);
  announce(`Generating ${bits}-bit RSA-OAEP key pair via WebCrypto…`);

  const t0 = performance.now();
  try {
    const pair = await crypto.subtle.generateKey(
      {
        name: 'RSA-OAEP',
        modulusLength: bits,
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]), // 65537
        hash: 'SHA-256',
      },
      false, // non-extractable private key (security best practice)
      ['encrypt', 'decrypt'],
    ) as CryptoKeyPair;

    const kgTime = Math.round(performance.now() - t0);
    oaepKeys[bits] = {
      publicKey:  pair.publicKey,
      privateKey: pair.privateKey,
      bits,
    };

    // Update timing
    setText(`oaep-${bits}-kg-time`, String(kgTime));
    show(`oaep-${bits}-timing`);

    // Enable encrypt buttons
    (document.getElementById('oaep-encrypt-2048') as HTMLButtonElement).disabled = !oaepKeys[2048];
    (document.getElementById('oaep-encrypt-4096') as HTMLButtonElement).disabled = !oaepKeys[4096];

    show('oaep-encrypt-card');
    announce(`${bits}-bit RSA-OAEP key pair generated in ${kgTime} ms.`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Key generation failed: ${msg}`);
  } finally {
    setLoading(btn, false, originalLabel);
  }
}

/* ── Encrypt ────────────────────────────────────────────────── */
async function doEncrypt(bits: 2048 | 4096): Promise<void> {
  const kp = oaepKeys[bits];
  if (!kp) { announce('Generate the key first.'); return; }

  const input = document.getElementById('oaep-plaintext') as HTMLTextAreaElement;
  const pt = new TextEncoder().encode(input.value);

  // OAEP-SHA256 max plaintext: k − 2*hLen − 2 bytes = modBytes − 66 bytes
  const maxBytes = bits / 8 - 66;
  if (pt.length > maxBytes) {
    announce(`Message too long. Maximum ${maxBytes} bytes for ${bits}-bit key with SHA-256.`);
    return;
  }

  const btnId = `oaep-encrypt-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce(`Encrypting with RSA-${bits}-OAEP…`);

  const t0 = performance.now();
  try {
    const ct = await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt);
    const encTime = Math.round(performance.now() - t0);

    lastCiphertext     = ct;
    lastCiphertextBits = bits;

    // Compute the OAEP-encoded intermediate fields (independent random seed)
    // so the diagram hover can show real bytes for the user's plaintext.
    try { lastOaepFields = await oaepEncode(pt, bits / 8); } catch { lastOaepFields = null; }

    const b64 = toBase64(new Uint8Array(ct));
    setText('oaep-ciphertext', b64);
    show('oaep-encrypt-result');

    // Update timing
    setText(`oaep-${bits}-enc-time`, String(encTime));

    // Enable decrypt buttons
    (document.getElementById('oaep-decrypt-2048') as HTMLButtonElement).disabled = bits !== 2048;
    (document.getElementById('oaep-decrypt-4096') as HTMLButtonElement).disabled = bits !== 4096;

    show('oaep-decrypt-card');
    show('oaep-randomize-card');
    announce(`Encrypted in ${encTime} ms. Ciphertext is ${ct.byteLength} bytes.`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Encryption failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}

/* ── Decrypt ────────────────────────────────────────────────── */
async function doDecrypt(bits: 2048 | 4096): Promise<void> {
  const kp = oaepKeys[bits];
  if (!kp || !lastCiphertext) { announce('Encrypt a message first.'); return; }
  if (lastCiphertextBits !== bits) {
    announce(`Ciphertext was encrypted with ${lastCiphertextBits}-bit key. Cannot decrypt with ${bits}-bit key.`);
    return;
  }

  const btnId = `oaep-decrypt-${bits}`;
  const btn = document.getElementById(btnId) as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce(`Decrypting with RSA-${bits}-OAEP…`);

  const t0 = performance.now();
  try {
    const pt = await crypto.subtle.decrypt({ name: 'RSA-OAEP' }, kp.privateKey, lastCiphertext);
    const decTime = Math.round(performance.now() - t0);
    const text = new TextDecoder().decode(pt);

    // Update timing
    setText(`oaep-${bits}-dec-time`, String(decTime));

    // Show result
    const outputEl = document.getElementById('oaep-decrypt-output') as HTMLElement;
    const statusEl = document.getElementById('oaep-decrypt-status') as HTMLElement;
    const textEl   = document.getElementById('oaep-decrypt-text')   as HTMLElement;

    outputEl.classList.add('result-box-success');
    statusEl.textContent = `✓ Decryption successful (${decTime} ms)`;
    textEl.textContent   = text;
    show('oaep-decrypt-output');
    announce(`Decrypted successfully in ${decTime} ms. Recovered: "${text}"`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    const outputEl = document.getElementById('oaep-decrypt-output') as HTMLElement;
    const statusEl = document.getElementById('oaep-decrypt-status') as HTMLElement;
    const textEl   = document.getElementById('oaep-decrypt-text')   as HTMLElement;

    outputEl.className = 'result-box result-box-error';
    statusEl.textContent = '✗ Decryption failed';
    textEl.textContent   = msg;
    show('oaep-decrypt-output');
    announce(`Decryption failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}

/* ── Randomization demo ─────────────────────────────────────── */
async function demonstrateRandomization(): Promise<void> {
  // Use whichever key pair is available
  const bits: 2048 | 4096 = oaepKeys[2048] ? 2048 : oaepKeys[4096] ? 4096 : 2048;
  const kp = oaepKeys[bits];
  if (!kp) {
    announce('Generate a key pair first.');
    return;
  }

  const input = document.getElementById('oaep-plaintext') as HTMLTextAreaElement;
  const pt = new TextEncoder().encode(input.value);
  const maxBytes = bits / 8 - 66;
  if (pt.length > maxBytes) {
    announce('Message too long for randomization demo.');
    return;
  }

  const btn = document.getElementById('oaep-randomize') as HTMLButtonElement;
  const lbl = btn.getAttribute('aria-label') ?? '';
  setLoading(btn, true);
  announce('Encrypting same message twice to demonstrate randomization…');

  try {
    const [ct1, ct2] = await Promise.all([
      crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt),
      crypto.subtle.encrypt({ name: 'RSA-OAEP' }, kp.publicKey, pt),
    ]);

    const b64_1 = toBase64(new Uint8Array(ct1));
    const b64_2 = toBase64(new Uint8Array(ct2));
    const match = b64_1 === b64_2;

    setText('oaep-ct1-short', truncate(b64_1, 52));
    setText('oaep-ct2-short', truncate(b64_2, 52));

    const matchEl = document.getElementById('oaep-ct-match') as HTMLElement;
    matchEl.textContent = match ? '⚠ YES (unexpected)' : '✓ NO — different every time';
    matchEl.style.color = match ? 'var(--c-danger)' : 'var(--c-safe)';

    show('oaep-randomize-result');
    announce(
      match
        ? 'Warning: ciphertexts matched unexpectedly.'
        : 'Confirmed: two encryptions of the same plaintext produce different ciphertexts.',
    );
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    announce(`Randomization demo failed: ${msg}`);
  } finally {
    setLoading(btn, false, lbl);
  }
}
